package container

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/jinmugo/sls/internal/util"
)

// GenerateIncludeFile creates the SSH config include file at the given path
// with Host entries for all cached containers. Uses ProxyJump to route through
// the parent host, so all parent SSH config (keys, proxies, etc.) is inherited.
func GenerateIncludeFile(cache *Cache, outputPath string) error {
	if len(cache.Hosts) == 0 {
		return fmt.Errorf("no cached containers. Run `sls discover <host>` first")
	}

	var b strings.Builder
	b.WriteString("# Auto-generated by sls — do not edit manually\n")
	b.WriteString("# Re-run `sls gen ssh-config` to update\n\n")

	for hostAlias, hc := range cache.Hosts {
		if len(hc.Containers) == 0 {
			continue
		}

		for _, c := range hc.Containers {
			// Skip containers with no shell
			if c.Shell == ShellNone {
				continue
			}
			// Host line uses display name for user convenience
			alias := hostAlias + KeySep + c.DisplayName()
			b.WriteString(fmt.Sprintf("Host %s\n", alias))
			// Route through the parent host — inherits all SSH config automatically
			b.WriteString(fmt.Sprintf("    ProxyJump %s\n", hostAlias))
			// Use detected shell if available, fall back to /bin/sh
			shell := ShellSh
			if c.Shell != "" && c.Shell != ShellNone {
				shell = c.Shell
			}
			b.WriteString(fmt.Sprintf("    RemoteCommand docker exec -it %s %s\n", c.Name, shell))
			b.WriteString("    RequestTTY yes\n")
			b.WriteString("\n")
		}
	}

	return util.AtomicWriteFile(outputPath, []byte(b.String()), 0o600)
}

// DefaultIncludePath returns the default path for the generated SSH config include file.
func DefaultIncludePath() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(home, ".config", "sls", "ssh_config"), nil
}

// AddIncludeLine adds an `Include` directive to ~/.ssh/config if not already present.
// Uses raw text manipulation to avoid stripping comments.
func AddIncludeLine(sshConfigPath, includePath string) error {
	includeDirective := fmt.Sprintf("Include %s", includePath)

	data, err := os.ReadFile(sshConfigPath)
	if err != nil {
		if os.IsNotExist(err) {
			return fmt.Errorf("SSH config not found at %s", sshConfigPath)
		}
		return err
	}

	// Check if Include already exists
	content := string(data)
	scanner := bufio.NewScanner(strings.NewReader(content))
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == includeDirective {
			return nil // already present
		}
	}

	// Prepend Include at the top (Include directives must come before Host blocks)
	newContent := includeDirective + "\n\n" + content
	return util.AtomicWriteFile(sshConfigPath, []byte(newContent), 0o600)
}
